services:
  cf_sim:
    build: .
    container_name: crazyflie_sim
    ports:
      - "6080:6080"  # noVNC web interface
      - "5901:5901"  # VNC server
    volumes:
      - ./src:/root/ros2_ws/src
    stdin_open: true
    tty: true
  